services:
  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    restart: unless-stopped
    ports:
      - "3000:8080"
    volumes:
      - openwebui-data:/app/backend/data
    environment:
      - ENABLE_PERSISTENT_CONFIG=false

      - ENABLE_SIGNUP=true
      - ENABLE_LOGIN_FORM=true
    env_file:
      - .env

volumes:
  openwebui-data:
